### ISSUE TITLE
#TK97 Crear vista Secundaria de Dashboard admin xml tal cual como se hizó con servicios y usuarios.

### ISSUE THREAD

**Issue by BraianTroncoso** [grupo-ispc-2023-2-0/workflix-app#257]
![WhatsApp Image 2023-10-22 at 22 05 34](https://github.com/grupo-ispc-2023-2-0/workflix-app/assets/95662710/25314e71-aded-44a4-b98c-6d93e23615b4)

También se debe agregar los 3 botones que se ven en img, tiene que ser exactamente igual, se debe re utilizar código ya existente solamente adaptar los valores para que sea admin, en lugar de servicio o usuario.

**Comment by NataliaAlvarezIspc** [comment]
Los admin se crean desde la base de datos(ej. Workbench) esta vista es innecesaria

**Comment by NataliaAlvarezIspc** [comment]
hecha en rama de tk96
