### ISSUE TITLE
#TK98 Darle funcionalidad al boton administradores

### ISSUE THREAD

**Issue by BraianTroncoso** [grupo-ispc-2023-2-0/workflix-app#258]
![c](https://github.com/grupo-ispc-2023-2-0/workflix-app/assets/95662710/264b0e90-bc01-4e83-894e-4fa8e4f4883e)

Al hacer click tiene que llevarte a la vista principal para visualizar los usuarios administradores.
Esta tarea esta condicionada a la #257 y a la #256

**Comment by NataliaAlvarezIspc** [comment]
hecha en  rama tk96
