### ISSUE TITLE
#TK 121 - Editar video demo final sprint 2

### ISSUE THREAD

**Issue by yan0106** [grupo-ispc-2023-2-0/workflix-app#326]

**Comment by NataliaAlvarezIspc** [comment]
El video se sube a la wiki en la siguiente ruta
[github.com/grupo-ispc-2023-2-0/workflix-app/wiki/Video-Demo-Sprint-2](https://github.com/grupo-ispc-2023-2-0/workflix-app/wiki/Video-Demo-Sprint-2)

**Comment by yan0106** [comment]
Presentación Grupal Cierre Sprint 2: 

https://youtu.be/gzRE61qzoVY

Demo Funcional Sprint 2:

https://youtu.be/_YPBTWhqj3Q

**Comment by yan0106** [comment]
se agregan enlaces en la wiki y en readme
