### ISSUE TITLE
#TK02 Crear filtro por servicio

### ISSUE THREAD

**Issue by NataliaAlvarezIspc** [grupo-ispc-2023-2-0/workflix-app#5]
- [x] #78
- [x] #79

**Comment by marceloedelgado** [comment]
Se han creado los botones de filtro para la activity_catalogo.xml en la seccion HorizontalScrollView con estilo pildoras igual al diseño UX, tiene movimiento lateral funcionando

**Comment by marceloedelgado** [comment]
En proximas tareas en Sprint 2 se le dara funcionalidad
